import React,{useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter,useNavigate,useParams,NavLink} from 'react-router-dom'
import {Routes,Route} from 'react-router-dom'
import {Activity,ShieldAlert,Radio,Plus,ExternalLink,RefreshCw,Wifi,ChevronRight,CheckCircle2,AlertTriangle,Scale,Archive,Clock,Send} from 'lucide-react'
import {useWallet} from './hooks/useWallet'
import {useProofPulse} from './hooks/useProofPulse'
import {CONTRACT_ADDRESS,explorerAddress} from './config/chains'
import './styles.css'

const short=a=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'—'
const statusClass=s=>String(s||'').toLowerCase().replaceAll('_','-')
function Shell({wallet,app,children}){return <div className="shell"><header><div className="brand"><div className="pulse"><Activity size={22}/></div><div><b>ProofPulse</b><span>INFRASTRUCTURE ACCOUNTABILITY</span></div></div><nav><NavLink to="/">Command Center</NavLink><NavLink to="/services">Services</NavLink><NavLink to="/incidents">Incidents</NavLink><NavLink to="/docs">Protocol</NavLink></nav><div className="head-actions"><a className="explorer" href={explorerAddress()} target="_blank">Explorer <ExternalLink size={14}/></a><button className="wallet" onClick={()=>wallet.connect().catch(e=>alert(e.message))}>{wallet.account?short(wallet.account):'Connect Wallet'}</button></div></header><main>{app.tx&&<a className="txbar" target="_blank" href={app.explorerTx(app.tx.hash)}>Transaction {app.tx.status}: {short(app.tx.hash)} <ExternalLink size={14}/></a>}{children}</main></div>}
function Dashboard({app}){const active=app.services.filter(s=>s.status==='ACTIVE').length;const resolved=app.incidents.filter(i=>['RESOLVED','APPEAL_RESOLVED','CLOSED'].includes(i.status)).length;return <><section className="hero"><div><div className="eyebrow"><Radio size={14}/> LIVE ON GENLAYER STUDIONET</div><h1>Infrastructure<br/><em>under consensus.</em></h1><p>ProofPulse turns infrastructure reliability disputes into evidence-bound, adversarial cases resolved through GenLayer consensus.</p><div className="hero-buttons"><NavLink className="primary" to="/services/new"><Plus/> Register service</NavLink><NavLink className="secondary" to="/incidents/new"><ShieldAlert/> Open incident</NavLink></div></div><div className="orb"><div className="orbcore"><Wifi size={58}/><span>CONSENSUS<br/>ONLINE</span></div></div></section><section className="stats"><Stat n={app.services.length} l="Registered services"/><Stat n={active} l="Active commitments"/><Stat n={app.incidents.length} l="Incident cases"/><Stat n={resolved} l="Resolved outcomes"/></section><section className="grid"><div className="panel wide"><div className="panelhead"><div><span className="kicker">NETWORK REGISTRY</span><h2>Service pulse</h2></div><NavLink to="/services">View all <ChevronRight size={16}/></NavLink></div>{app.loading?<div className="empty">Scanning on-chain registry…</div>:app.services.length?app.services.slice(0,5).map(s=><NavLink className="service-row" to={`/services/${s.service_id}`} key={String(s.service_id)}><span className={`dot ${statusClass(s.status)}`}></span><div><b>{s.title}</b><small>{s.endpoint}</small></div><span className={`badge ${statusClass(s.status)}`}>{s.status}</span><ChevronRight/></NavLink>):<Empty icon={<Radio/>} text="No services registered yet."/>}</div><div className="panel"><span className="kicker">PROTOCOL</span><h2>12-step accountability</h2><div className="steps">{['Create','Commit','Activate','Incident','Observe','Respond','Challenge','Resolve','Appeal','Re-resolve','Close','Archive'].map((x,i)=><div key={x}><i>{String(i+1).padStart(2,'0')}</i>{x}</div>)}</div></div></section></>}
const Stat=({n,l})=><div className="stat"><b>{n}</b><span>{l}</span></div>
const Empty=({icon,text})=><div className="empty">{icon}<span>{text}</span></div>
function Services({app}){return <Page title="Service Registry" sub="Every endpoint begins as a locked commitment before incidents can exist."><div className="toolbar"><NavLink className="primary" to="/services/new"><Plus/> Register service</NavLink><button className="ghost" onClick={app.refresh}><RefreshCw size={16}/> Refresh</button></div><div className="cards">{app.services.map(s=><NavLink to={`/services/${s.service_id}`} className="card" key={String(s.service_id)}><div className="cardtop"><span className={`badge ${statusClass(s.status)}`}>{s.status}</span><Activity/></div><h3>{s.title}</h3><p>{s.summary}</p><code>{s.endpoint}</code><div className="meta"><span>HTTP {String(s.target_success_code)}</span><span>{String(s.incident_count)} incidents</span></div></NavLink>)}</div>{!app.loading&&!app.services.length&&<Empty icon={<Radio/>} text="The registry is waiting for its first service."/>}</Page>}
function Incidents({app}){return <Page title="Incident Desk" sub="Claims, observations, challenges, consensus and appeals—one evidence-bound timeline."><div className="toolbar"><NavLink className="primary" to="/incidents/new"><Plus/> Open incident</NavLink></div><div className="timeline-list">{app.incidents.map(i=><NavLink to={`/incidents/${i.incident_id}`} className="incident" key={String(i.incident_id)}><span className={`signal ${statusClass(i.status)}`}></span><div><span className="mono">CASE #{String(i.incident_id).padStart(4,'0')}</span><h3>{i.claim_text}</h3><small>Service #{String(i.service_id)} · {i.observation_count} observations</small></div><span className={`badge ${statusClass(i.status)}`}>{i.outcome==='INCONCLUSIVE'?i.status:i.outcome}</span><ChevronRight/></NavLink>)}</div>{!app.loading&&!app.incidents.length&&<Empty icon={<ShieldAlert/>} text="No incidents on record."/>}</Page>}
function NewService({app}){const [f,setF]=useState({endpoint:'https://example.com',title:'',summary:'',code:'200',commitment:''});const [step,setStep]=useState(1);const submit=async()=>{try{if(step===1){const r=await app.write('create_service',[f.endpoint,f.title,f.summary]);setF({...f,id:r.hash?null:null});alert('Service created. Refresh and note the returned service ID from transaction/registry.');setStep(2)}else if(step===2){const id=prompt('Enter the Service ID returned by create_service');if(!id)return;await app.write('define_commitment',[BigInt(id),BigInt(f.code),f.commitment]);await app.write('activate_service',[BigInt(id)]);alert('Service commitment activated.');location.hash='#/services'}}catch(e){alert(e.message)}};return <Page title="Register Infrastructure" sub="Lock an endpoint and commitment before anyone can open an incident."><div className="form panel"><Step n="01" title="Service identity"/><Input label="HTTPS endpoint" value={f.endpoint} onChange={v=>setF({...f,endpoint:v})}/><Input label="Service title" value={f.title} onChange={v=>setF({...f,title:v})}/><Text label="What does this service provide?" value={f.summary} onChange={v=>setF({...f,summary:v})}/>{step===2&&<><Step n="02" title="Reliability commitment"/><Input label="Expected HTTP success code" value={f.code} onChange={v=>setF({...f,code:v})}/><Text label="Locked commitment criteria" value={f.commitment} onChange={v=>setF({...f,commitment:v})}/></>}<button className="primary" onClick={submit}><Send/> {step===1?'Create service':'Lock & activate'}</button></div></Page>}
function NewIncident({app}){const [f,setF]=useState({service:'',start:'',end:'',claim:''});const submit=async()=>{try{await app.write('open_incident',[BigInt(f.service),BigInt(f.start),BigInt(f.end),f.claim]);alert('Incident opened');location.hash='#/incidents'}catch(e){alert(e.message)}};return <Page title="Open Incident" sub="Anchor a claim to one active service and one closed observation window."><div className="form panel"><Input label="Service ID" value={f.service} onChange={v=>setF({...f,service:v})}/><Input label="Window start (Unix seconds)" value={f.start} onChange={v=>setF({...f,start:v})}/><Input label="Window end (Unix seconds)" value={f.end} onChange={v=>setF({...f,end:v})}/><Text label="Incident claim" value={f.claim} onChange={v=>setF({...f,claim:v})}/><button className="primary" onClick={submit}><ShieldAlert/> Open evidence-bound incident</button></div></Page>}
function ServiceDetail({app}){const {id}=useParams();const s=app.services.find(x=>String(x.service_id)===id);if(!s)return <Page title="Service not loaded"><Empty icon={<Activity/>} text="Refresh the registry or check the ID."/></Page>;const archive=()=>app.write('archive_service',[BigInt(id)]).then(()=>alert('Archived')).catch(e=>alert(e.message));return <Page title={s.title} sub={s.endpoint}><div className="detail-grid"><div className="panel"><span className={`badge ${statusClass(s.status)}`}>{s.status}</span><h2>{s.title}</h2><p>{s.summary}</p><div className="commit"><span>LOCKED COMMITMENT</span><b>HTTP {String(s.target_success_code)}</b><p>{s.commitment_text||'Commitment not defined'}</p></div></div><div className="panel"><span className="kicker">SERVICE CONTROL</span><h2>Lifecycle</h2><div className="actions"><NavLink className="primary" to="/incidents/new">Open incident</NavLink>{s.status==='ACTIVE'&&<button className="danger" onClick={archive}><Archive/> Archive service</button>}</div><div className="meta-stack"><span>Provider <code>{short(s.provider)}</code></span><span>Incidents <b>{String(s.incident_count)}</b></span></div></div></div></Page>}
function IncidentDetail({app}){const {id}=useParams();const i=app.incidents.find(x=>String(x.incident_id)===id);if(!i)return <Page title="Incident not loaded"><Empty icon={<ShieldAlert/>} text="Refresh the incident desk."/></Page>;const action=async(fn,args)=>{try{await app.write(fn,args);alert(fn+' submitted');app.refresh()}catch(e){alert(e.message)}};return <Page title={`Case #${String(i.incident_id).padStart(4,'0')}`} sub={`Service #${String(i.service_id)} · ${i.status}`}><div className="detail-grid"><div className="panel"><span className={`badge ${statusClass(i.status)}`}>{i.status}</span><h2>Claim</h2><p>{i.claim_text}</p><div className="commit"><span>OBSERVATION WINDOW</span><b>{String(i.window_start)} → {String(i.window_end)}</b><p>{String(i.observation_count)} structured observations recorded.</p></div>{i.provider_response&&<div className="response"><span>PROVIDER RESPONSE</span>{i.provider_response}</div>}{i.challenge_reason&&<div className="response warn"><span>CHALLENGE</span>{i.challenge_reason}</div>}</div><div className="panel"><span className="kicker">CONSENSUS CONTROL</span><h2>{i.outcome||'Awaiting resolution'}</h2><p>{i.summary||'The case has not reached consensus yet.'}</p><div className="actions">{['OPEN','CHALLENGED'].includes(i.status)&&<><button onClick={()=>{let t=prompt('Observed at (Unix seconds)');let c=prompt('Observed HTTP code');let n=prompt('Note');if(t&&c)action('submit_observation',[BigInt(id),BigInt(t),BigInt(c),n||''])}}>Add observation</button><button onClick={()=>action('respond_to_incident',[BigInt(id),prompt('Provider response')||''])}>Respond</button><button onClick={()=>action('challenge_observation',[BigInt(id),prompt('Challenge reason')||''])}>Challenge</button><button className="primary" onClick={()=>action('resolve_incident',[BigInt(id)])}><Scale/> Resolve consensus</button></>}{i.status==='RESOLVED'&&<button className="primary" onClick={()=>action('appeal_incident',[BigInt(id),prompt('Appeal reason')||''])}>Appeal verdict</button>}{i.status==='APPEALED'&&<button className="primary" onClick={()=>action('resolve_appeal',[BigInt(id)])}>Resolve appeal</button>}{['RESOLVED','APPEAL_RESOLVED'].includes(i.status)&&<button onClick={()=>action('close_incident',[BigInt(id)])}><CheckCircle2/> Close incident</button>}</div></div></div><div className="protocol-line">{['OPEN','CHALLENGED','RESOLVED','APPEALED','APPEAL_RESOLVED','CLOSED'].map(x=><div className={i.status===x?'current':''} key={x}><i></i>{x.replaceAll('_',' ')}</div>)}</div></Page>}
function Docs(){return <Page title="Protocol Architecture" sub="Why ProofPulse uses consensus, locked evidence and independent appeal rounds."><div className="docs panel"><h2>Evidence before verdict</h2><p>A provider locks an HTTPS endpoint and success criteria before activation. Incident windows are immutable once opened. Resolution derives external checks from those locked identifiers.</p><h2>Adversarial by design</h2><p>Claimants and providers have opposing incentives over reliability outcomes. GenLayer consensus adjudicates the dispute rather than acting as a decorative oracle.</p><h2>Four reachable outcomes</h2><div className="outcomes"><b>INCONCLUSIVE</b><b>SLA MET</b><b>PARTIAL BREACH</b><b>SLA BREACHED</b></div><h2>Fresh appeal round</h2><p>An appeal does not merely reread the first result. It triggers a new nondeterministic consensus round against canonical sources.</p><a className="explorer" href={explorerAddress()} target="_blank">Inspect deployed contract <ExternalLink size={15}/></a></div></Page>}
function Page({title,sub,children}){return <section className="page"><div className="pagehead"><div><span className="kicker">PROOFPULSE / STUDIONET</span><h1>{title}</h1>{sub&&<p>{sub}</p>}</div></div>{children}</section>}
function Input({label,value,onChange}){return <label>{label}<input value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Text({label,value,onChange}){return <label>{label}<textarea rows="5" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Step({n,title}){return <div className="formstep"><i>{n}</i><b>{title}</b></div>}
function App(){const wallet=useWallet();const app=useProofPulse(wallet.account,wallet.ensureChain);return <Shell wallet={wallet} app={app}><Routes><Route path="/" element={<Dashboard app={app}/>}/><Route path="/services" element={<Services app={app}/>}/><Route path="/services/new" element={<NewService app={app}/>}/><Route path="/services/:id" element={<ServiceDetail app={app}/>}/><Route path="/incidents" element={<Incidents app={app}/>}/><Route path="/incidents/new" element={<NewIncident app={app}/>}/><Route path="/incidents/:id" element={<IncidentDetail app={app}/>}/><Route path="/docs" element={<Docs/>}/></Routes></Shell>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>)